[profile.cpu]
region = "eu-west-3"
image_id = "ami-05e8e219ac7e82eba" # ubuntu 22.04
instance_type = "t3.micro"
#instance_type = "m6g.large"
subnet_id = "subnet-0e042c7621461f754"

# Handling backends
[backend.aws.cpu]
region = "eu-west-3"
image_id = "ami-05e8e219ac7e82eba" # ubuntu 22.04
instance_type = "t3.xlarge"
#instance_type = "t345.xlarge" # Non existing instance type

[backend.aws.cpu_fallback]
region = "eu-west-3"
image_id = "ami-05e8e219ac7e82eba" # ubuntu 22.04
instance_type = "t3.xlarge"

[profile.cpu_fallback]
region = "us-east-1"
image_id = "ami-0c4773f5626d919b6"
instance_type = "p3.2xlarge"

#[backend.hyperstack.gpu]
#environment_name = "norway"
#volume_name = "slab-server-tests"
#flavor_name = "n1-cpu-small"

[backend.hyperstack.gpu]
environment_name = "canada"
volume_name = "slab-server-tests"
flavor_name = "m"

[profile.gpu]
region = "eu-west-1"  # Ireland
image_id = "ami-0261faf04cf54fe0a"  # GPU image in eu-west-1 to test auto retry
instance_type = "p3.2xlarge"

[profile.gpu-bench]
region = "us-west-2"
image_id = "ami-02ae9b9b4fffdf66f"
instance_type = "p5.48xlarge"
max_spot_price = "200.49"

[command.cpu_test]
workflow = "main.yml"
profile = "cpu"
check_run_name = "AWS tests (Slab)"
#matrix = [2, 4, 6]
#max_parallel_jobs = 2

[command.gpu_test]
workflow = "main.yml"
profile = "gpu-bench"
check_run_name = "AWS tests spawn GPU (Slab)"

