[profile.cpu]
region = "eu-west-3"
image_id = "ami-05e8e219ac7e82eba" # ubuntu 22.04
#instance_type = "t3.micro"
instance_type = "m6g.large"
subnet_id = "subnet-0e042c7621461f754"

[profile.cpu_fallback]
region = "us-east-1"
image_id = "ami-0c4773f5626d919b6"
instance_type = "p3.2xlarge"

[profile.gpu]
region = "eu-west-1"  # Ireland
image_id = "ami-0261faf04cf54fe0a"  # GPU image in eu-west-1 to test auto retry
instance_type = "p3.2xlarge"

[command.cpu_test]
workflow = "main.yml"
profile = "cpu"
check_run_name = "AWS tests (Slab)"
#matrix = [2, 4, 6]
#max_parallel_jobs = 2

[command.gpu_test]
workflow = "main.yml"
profile = "gpu"
check_run_name = "AWS tests spawn GPU (Slab)"

